# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://iamilam.github.io/moonrise"
baseurl: "/moonrise"
siteIcon: media/android-chrome-192x192.png
siteYear: 2021
siteFooterlink: about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: The Pseudo Force SMP
serverDescription: Fun Cross-Platform Survival Multiplayer!
serverIP: pseudosmp.serveminecraft.net


# Discord information
discordInvite: http://dsc.gg/pseudosmp
discordServerID: 842779800694947840
discordChannelID: 843181401461358632

# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
