# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
 schedule: 
  - cron: "15 16 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: kshehadeh/jekyll-s3-action@0.1
      # Runs a single command using the runners shell
        with:
          token: "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"
